
import p18500 from '../assets/Premium Blended Fleece Pullover.png';
import p4000 from '../assets/Premium Black Fleece Pullover.png';
import mineralTee from '../assets/Mineral Wash Tee.png';
import babyTee from '../assets/Premium Baby Tee.png';
import boyfriendTee from '../assets/Premium Boyfriend Tee.png';
import cropTee from '../assets/Jersey Boxy Crop Tee.png';
import ribBoxyCropTee from '../assets/Rib Boxy Crop Tee.png';
import mineralTeeGray from '../assets/Mineral Wash Tee-grey.png';
import babyTeeWhite from '../assets/Premium Baby Tee-white.png';
import cropTeeWhite from '../assets/Jersey Boxy Crop Tee-white.png';
import ribBoxyCropTeeWhite from '../assets/Rib Boxy Crop Tee-white.png';

const products = [
  {
    sku: 'PT-18500',
    slug: 'pt-18500',
    category: 'men',
    categoryLabel: 'MEN',
    backLabel: 'BACK TO MEN',
    backPath: '/inventory/men',
    name: 'Premium Blended Fleece Pullover',
    tagline: '8 Ounce Premium Blended Fleece Pullover',
    image: p18500,
    gsm: 280,
    weight: '8 oz',
    packing: '25 pieces per carton',
    fabric: 'Blended fleece — soft hand, structured drape.',
    colors: null,
    inventoryLabel: 'In stock now',
    sizes: [
      { size: 'XXS', units: null },
      { size: 'XS', units: 150 },
      { size: 'S', units: 13113 },
      { size: 'M', units: 20912 },
      { size: 'L', units: 11729 },
      { size: 'XL', units: 1740 },
      { size: 'XXL', units: 1110 },
    ],
    totalUnits: 48754,
  },
  {
    sku: 'PT-4000',
    slug: 'pt-4000',
    category: 'men',
    categoryLabel: 'MEN',
    backLabel: 'BACK TO MEN',
    backPath: '/inventory/men',
    name: 'Premium Black Fleece Pullover',
    tagline: '10 Ounce Premium Black Fleece Pullover',
    image: p4000,
    gsm: 340,
    weight: '10 oz',
    packing: '12 pieces per pack',
    fabric: 'Heavyweight fleece — dense, durable, weighty drape.',
    colors: null,
    inventoryLabel: 'In stock now',
    sizes: [
      { size: 'S', units: 128 },
      { size: 'M', units: 872 },
      { size: 'L', units: 2788 },
      { size: 'XL', units: 2707 },
      { size: 'XXL', units: 1076 },
    ],
    totalUnits: 7571,
  },
  {
    sku: 'PT-5000-MW',
    slug: 'pt-5000-mw',
    category: 'men',
    categoryLabel: 'MEN',
    backLabel: 'BACK TO MEN',
    backPath: '/inventory/men',
    name: 'Mineral Wash Tee',
    tagline: '100% Cotton Mineral Wash Tee',
    image: mineralTee,
    gsm: 180,
    weight: '5.3 oz',
    packing: null,
    fabric: '100% cotton, garment-dyed mineral wash. Lived-in texture from the first wear.',
    colors: [
      { name: 'Black', selected: true, image: mineralTee },
      { name: 'Gray', selected: false, image: mineralTeeGray },
    ],
    inventoryLabel: 'Black — in stock',
    sizes: [
      { size: 'S', units: 13860 },
      { size: 'M', units: 21180 },
      { size: 'L', units: 21060 },
      { size: 'XL', units: 11520 },
      { size: 'XXL', units: 3900 },
    ],
    totalUnits: 71520,
  },
  {
    sku: 'W2017',
    slug: 'w2017',
    category: 'women',
    categoryLabel: 'WOMEN',
    backLabel: 'BACK TO WOMEN',
    backPath: '/inventory/women',
    name: 'Premium Baby Tee',
    tagline: '50/50 Cotton-Poly 1x1 Rib Baby Tee',
    image: babyTee,
    gsm: 180,
    weight: '5.3 oz',
    packing: null,
    fabric: '50% cotton / 50% polyester, 1x1 baby rib. Soft hand with structured stretch.',
    colors: [
      { name: 'Natural', selected: true, image: babyTee },
      { name: 'White', selected: false, image: babyTeeWhite },
    ],
    inventoryLabel: 'Natural — in stock',
    sizes: [
      { size: 'S', units: 398 },
      { size: 'M', units: 798 },
      { size: 'L', units: 800 },
      { size: 'XL', units: 400 },
      { size: 'XXL', units: 400 },
    ],
    totalUnits: 2796,
  },
  {
    sku: 'W2012',
    slug: 'w2012',
    category: 'women',
    categoryLabel: 'WOMEN',
    backLabel: 'BACK TO WOMEN',
    backPath: '/inventory/women',
    name: 'Premium Boyfriend Tee',
    tagline: '60/40 Cotton-Poly Jersey Boyfriend Tee',
    image: boyfriendTee,
    gsm: 150,
    weight: '4.4 oz',
    packing: null,
    fabric: '60% cotton / 40% polyester jersey. Relaxed boyfriend silhouette with a smooth, breathable hand.',
    colors: null,
    inventoryLabel: 'In stock now',
    sizes: [
      { size: 'S', units: 398 },
      { size: 'M', units: 798 },
      { size: 'L', units: 800 },
      { size: 'XL', units: 400 },
      { size: 'XXL', units: 400 },
    ],
    totalUnits: 2796,
  },
  {
    sku: 'W2036',
    slug: 'w2036-145',
    category: 'women',
    categoryLabel: 'WOMEN',
    backLabel: 'BACK TO WOMEN',
    backPath: '/inventory/women',
    name: 'Jersey Boxy Crop Tee',
    tagline: '100% Cotton Jersey Boxy Crop Tee',
    image: cropTee,
    gsm: 145,
    weight: '4.3 oz',
    packing: null,
    fabric: '100% cotton jersey. Lightweight, boxy cropped silhouette with a clean shoulder line.',
    colors: [
      { name: 'Natural', selected: true, image: cropTee },
      { name: 'White', selected: false, image: cropTeeWhite },
    ],
    inventoryLabel: 'Natural — in stock',
    sizes: [
      { size: 'S', units: 182 },
      { size: 'M', units: 366 },
      { size: 'L', units: 368 },
      { size: 'XL', units: 184 },
      { size: 'XXL', units: 400 },
    ],
    totalUnits: 1500,
  },
  {
    sku: 'W2036',
    slug: 'w2036-180',
    category: 'women',
    categoryLabel: 'WOMEN',
    backLabel: 'BACK TO WOMEN',
    backPath: '/inventory/women',
    name: 'Rib Boxy Crop Tee',
    tagline: '100% Cotton 1x1 Rib Boxy Crop Tee',
    image: ribBoxyCropTee,
    gsm: 180,
    weight: '5.3 oz',
    packing: null,
    fabric: '100% cotton 1x1 rib. Heavier, structured rib knit with a defined boxy crop.',
    colors: [
      { name: 'Natural', selected: true, image: ribBoxyCropTee },
      { name: 'White', selected: false, image: ribBoxyCropTeeWhite },
    ],
    inventoryLabel: 'Natural — in stock',
    sizes: [
      { size: 'S', units: 398 },
      { size: 'M', units: 798 },
      { size: 'L', units: 800 },
      { size: 'XL', units: 400 },
      { size: 'XXL', units: 391 },
    ],
    totalUnits: 2787,
  },
];

export default products;

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}